feature(monitor): add is_template to terraform
* Updated descriptions/monitor.yaml for is_template
* Modified resource_monitor.go in resrouceMonitor(), newMonitorConfig to
handle the is_template flag.
NOTE: Intermediate monitor shape in go uses IsTemplate

TestPlan:
s/testbox start && terraform init && terraform apply
```
  # observe_monitor.transform_persistent_failure will be updated in-place
  ~ resource "observe_monitor" "transform_persistent_failure" {
        id          = "41000007"
      + is_template = true
        name        = "Transform Persistent Failure"
        # (4 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```
Note: Api will not create template unless disabled=False.

```
Error: failed to update monitor: input: monitor Template monitor 41000007 must be disabled

with observe_monitor.transform_persistent_failure,
   on main.tf line 15, in resource "observe_monitor" "transform_persistent_failure":
   15: resource "observe_monitor" "transform_persistent_failure" {
```
Related to ticket: OB-12580

Change-Id: I19c12a81e99a5f7af9ddebed70869e6da60e75d5